### ISSUE TITLE
获取ipv6地址失败错误

### ISSUE THREAD

**Issue by tangyl2000** [sanjusss/aliyun-ddns#10]
大佬，我用您这个docker有一段时间了，主要是用来动态ipv6地址解析。
但最近获取ipv6地址失败的机率较大。
我看了一下，您主要是用https://ipv6.lookup.test-ipv6.com/ip/这个接口来获取本机ipv6地址的，而您代码里ipv4地址却有4个地址。

**Comment by sanjusss** [comment]
test-ipv6这个网站有点不稳定，我尝试增加本地读取ipv6地址试试。

**Comment by kelvin-law** [comment]
> test-ipv6这个网站有点不稳定，我尝试增加本地读取ipv6地址试试。

您好,最近几天,所有接口都获取不到ipv6地址,不管是unraid还是群晖,也试过重装或者重启爱快,都是一样

**Comment by sanjusss** [comment]
> > test-ipv6这个网站有点不稳定，我尝试增加本地读取ipv6地址试试。
> 
> 您好,最近几天,所有接口都获取不到ipv6地址,不管是unraid还是群晖,也试过重装或者重启爱快,都是一样

IPv6最好使用直接读取本地地址的方式。同时设置CHECKLOCAL和IPV6NETS，一般IPV6NETS设置为你现在IPv6的地址第一位数字的网段（例如240e::/16）。设置了CHECKLOCAL后就不能通过在线API获取IPv4的公网地址了。
