### ISSUE TITLE
获取ipv6地址失败错误

### ISSUE THREAD

**Issue by tangyl2000** [sanjusss/aliyun-ddns#11]
大佬，我用您这个docker有一段时间了，主要是用来动态ipv6地址解析。
但最近获取ipv6地址失败的机率较大。
我看了一下，您主要是用https://ipv6.lookup.test-ipv6.com/ip/这个接口来获取本机ipv6地址的，而您代码里ipv4地址却有4个地址。
建议您增加几个ipv6接口，我看这几个还可以，不知可否：
http://checkipv6.dyndns.com/
https://api-ipv6.ip.sb/ip
http://v6.ident.me/
https://api6.ipify.org/
小小的个人建议而已，麻烦您了~~~

**Comment by sanjusss** [comment]
我会使用这些接口的，如果有国内网站就好了

**Comment by tangyl2000** [comment]
> 我会使用这些接口的，如果有国内网站就好了

谢谢大佬啦

**Comment by sanjusss** [comment]
已经推送更新了，过一会儿应该就自动构建完成。

**Comment by tangyl2000** [comment]
> 已经推送更新了，过一会儿应该就自动构建完成。

谢谢，好用多了，非常感谢，果然是大佬，哈哈哈
