### ISSUE TITLE
国外IP检测服务造成的问题

### ISSUE THREAD

**Issue by vensterlz** [sanjusss/aliyun-ddns#12]
全局翻墙的情况下，如果使用国外的IP检测服务，偶尔会将IP更新为出口地址，造成比较尴尬的情况。

**Comment by vensterlz** [comment]
国内的3322服务运行了很多年应该非常稳定，可以考虑作为备选服务器http://ip.3322.net

**Comment by sanjusss** [comment]
增加了CNIPV4变量，设置为true后可以只使用国内服务器检测IPv4
