### ISSUE TITLE
docker可以加个web ui吗？

### ISSUE THREAD

**Issue by hy1205** [sanjusss/aliyun-ddns#16]
加个web ui 方便改配置。

**Comment by sanjusss** [comment]
我没开发过web，请看到这条的大家帮忙实现吧。

**Comment by ZzMark** [comment]
虽然难度不大，可web ui能做的功能很有限

- 显示目前状态
- 显示日志
- 修改配置

其中修改配置的话，就要涉及配置存放在哪里的问题，并不适合本项目

**Comment by sanjusss** [comment]
> 虽然难度不大，可web ui能做的功能很有限
> 
> * 显示目前状态
> * 显示日志
> * 修改配置
> 
> 其中修改配置的话，就要涉及配置存放在哪里的问题，并不适合本项目

确实。
