### ISSUE TITLE
运行时出现错误提示，获取xxx的所有记录时出现异常...跳过设置域名

### ISSUE THREAD

**Issue by oldcaptain-fury** [sanjusss/aliyun-ddns#17]
本人使用的qnap，QTS版本为4.4.2.1270.CHN，阿里云里静态输入ipv6地址用网页能进入nas管理页面。使用ContainerStation创建的aliyun-ddns，反复确认设置与要求一致。不明白反馈信息含义，求教大神！
设置：
![aliyun-ddns设置1](https://data.hao4k.cn/forum/202005/20/095136by457k445f1ag81q.jpg)
![aliyun-ddns设置2]https://data.hao4k.cn/forum/202005/20/095239qc59ql7cvvrqxxll.jpg)

问题描述：
![aliyun-ddns错误1](https://data.hao4k.cn/forum/202005/20/102907jqftfhog70hq5fff.jpg)
一次例外：
5月5日中午突然收到阿里云通知ip地址修改成功的通知，惊奇的登录nas查看，仅有这一次成功获取并更新的记录，期间并没有对nas做任何设置和改变。
![5月5日成功的例外](https://data.hao4k.cn/forum/202005/20/095340puiuj018gf1cmuua.jpg)

**Comment by sanjusss** [comment]
有可能是成都的endpoint节点问题，可以把cn-chengdu改成别的试试。

**Comment by anitazhaochen** [comment]
我也有同样的问题，今天突然就不行了。 以前使用的是默认endpoint， 现在改成了  

cn-shenzhen 重启问题依旧

**Comment by oldcaptain-fury** [comment]
又发现一个奇怪的问题，不知跟aliyun-ddns解析动态ip遇到错误这事儿是否有点关联。
用ipv6的电脑或手机通过在阿里注册的域名访问nas的管理页面，打开其他的程序都正常，也很快，就只有打开container station界面内容出不来，提示找不到www.XXX.xyz服务器的ip地址。
但是在家通过ipv4 内网地址192.168.1.3:5000访问管理页面或qlinkto.cn/XXXX访问管理页面，打开container station都是正常的，真是奇怪了。我记得5月初手动更新了最新的ipv6地址到阿里云域名解析中，通过ipv6打开container station是正常的。
![Container Station找不到XXXX xyz的服务器地址](https://data.hao4k.cn/forum/202005/21/092252f76edc3mxxvlvnm2.jpg)

**Comment by sanjusss** [comment]
@anitazhaochen @oldcaptain-fury  重新拉取镜像试试，也可以直接选择0.2.2版本。  
在刚刚更新的0.2.2版本中，删除了ENDPOINT选项，改成阿里云SDK的自动检测获取。

**Comment by anitazhaochen** [comment]
@sanjusss 新版本的可以了，感谢

**Comment by oldcaptain-fury** [comment]
@sanjusss 意思是ENDPOINT这个环境变量就不用设置了？

**Comment by sanjusss** [comment]
> @sanjusss 意思是ENDPOINT这个环境变量就不用设置了？

是的，现在是由阿里云那边决定用哪个ENDPOINT。

**Comment by oldcaptain-fury** [comment]
感谢大佬响应这么及时，我刚重新拉去了最新镜像并设置创建，但我遇到的问题还是依旧，反馈的信息还是跟之前一样。有兄弟用了新版就正常了，说明镜像没有问题，阿里云那边也没问题，我在想是我的ipv6 的网络环境问题吗，但阿里云网页上静态修改了域名解析的ip 地址通过域名能正常访问，会不会是我的container station配置问题，但也没看到这几个教程中有相关设置的说明，迷茫了

**Comment by oldcaptain-fury** [comment]
我试了很多种情况，创建时什么都不设置、把nas的时区设置为+5、把akid或akst随意设置，反馈记录信息中的主要内容跟正确设置了的基本一致，感觉我的nas就没有连上阿里云动态解析的这个接口。顺便问一下我以上的异常反馈是阿里云接口反馈的，还是大佬的这个aliyun-ddns反馈的呢？我觉得应该是阿里云反馈的，到找到阿里的客服，他叫我找软件供应商

**Comment by sanjusss** [comment]
> 我试了很多种情况，创建时什么都不设置、把nas的时区设置为+5、把akid或akst随意设置，反馈记录信息中的主要内容跟正确设置了的基本一致，感觉我的nas就没有连上阿里云动态解析的这个接口。顺便问一下我以上的异常反馈是阿里云接口反馈的，还是大佬的这个aliyun-ddns反馈的呢？我觉得应该是阿里云反馈的，到找到阿里的客服，他叫我找软件供应商

这异常提示表明是无法连接到阿里云，所以你的其他设置对它不会产生影响。你试试能不能用你的nas访问这个链接：[https://oss-cn-chengdu.aliyuncs.com/](https://oss-cn-chengdu.aliyuncs.com/)

**Comment by oldcaptain-fury** [comment]
不知道用nas怎么直接访问这个链接，用453bmini的HDMI接电视，用HybridDeskStaition混合桌面工作站里的浏览器打开的这个链接，跟你的图片信息一样，并且还是cn-hangzhou，也是一样的反馈
![cn-chengdu](https://user-images.githubusercontent.com/65635391/82684677-96095980-9c85-11ea-997b-2494a4802ffb.jpg)
![cn-hangzhou](https://user-images.githubusercontent.com/65635391/82684690-9ace0d80-9c85-11ea-9e8f-7ec50b7d2be3.jpg)

**Comment by sanjusss** [comment]
> 不知道用nas怎么直接访问这个链接，用453bmini的HDMI接电视，用HybridDeskStaition混合桌面工作站里的浏览器打开的这个链接，跟你的图片信息一样，并且还是cn-hangzhou，也是一样的反馈
> ![cn-chengdu](https://user-images.githubusercontent.com/65635391/82684677-96095980-9c85-11ea-997b-2494a4802ffb.jpg)
> ![cn-hangzhou](https://user-images.githubusercontent.com/65635391/82684690-9ace0d80-9c85-11ea-9e8f-7ec50b7d2be3.jpg)

这很奇怪，照理来说，容器无法访问阿里云dns api，这个地址也无法打开才对。暂时没找到问题所在。

**Comment by oldcaptain-fury** [comment]
现在最让我奇怪的就是前面描述的，用ipv6的电脑或手机通过域名访问nas的管理页面，打开其他的程序都正常，就只有打开container station界面内容出不来，提示找不到www.XXX.xyz服务器的ip地址。但在家通过ipv4 内网地址或qlinkto.cn/XXX访问管理页面，打开container station都是正常的。现在就想问问用qnap的，有ipv6地址的朋友试试，是否跟我一样的情况，如果不一样，只有先去找威联通客户把这个问题了解清楚了来，感觉现在的问题就出在container station用ipv6不能连接
