### ISSUE TITLE
可以增加一个@类型的ipv6解析吗？

### ISSUE THREAD

**Issue by gavinman100** [sanjusss/aliyun-ddns#18]
楼主好，刚刚在使用您的程序在解析ipv6地址，远程连接的过程中发现，无法打开container station，后来发现是缺少@类型的解析，所以想咨询一下能否增加一个@类型的ipv6解析。
再次感谢您的程序。

**Comment by sanjusss** [comment]
有没有试过域名设置为@.xxx.xx这种模式？

**Comment by gavinman100** [comment]
楼主你好，我刚刚试了一下，在阿里云手动添加了一条@.xxx.xx的AAAA类型解析记录（故意写错ipv6地址，原www.xxx.xx记录保留），程序启动后控制台输出的提示是“AAAA记录www.xxx.xxx不需要更新”，再登录阿里云查看，@.xxx.xx的ipv6也没有更新。是我的设置有误吗？

**Comment by gavinman100** [comment]
补充：删掉或者修改阿里云www.xxx.xx的ipv6解析记录，启动程序后都会重新增加一条记录，控制台输出提示：成功增加AAAA记录www.xxx.xx为2409…………

**Comment by sanjusss** [comment]
> 楼主你好，我刚刚试了一下，在阿里云手动添加了一条@.xxx.xx的AAAA类型解析记录（故意写错ipv6地址，原www.xxx.xx记录保留），程序启动后控制台输出的提示是“AAAA记录www.xxx.xxx不需要更新”，再登录阿里云查看，@.xxx.xx的ipv6也没有更新。是我的设置有误吗？

> 补充：删掉或者修改阿里云www.xxx.xx的ipv6解析记录，启动程序后都会重新增加一条记录，控制台输出提示：成功增加AAAA记录www.xxx.xx为2409…………

我本地测试是可以成功设置@记录的（更新A和AAAA用的是同一个函数）。
![image](https://user-images.githubusercontent.com/8220722/84023872-74b1a880-a9bb-11ea-9e14-01000e8d850d.png)
DOMAIN变量是这么填的
![image](https://user-images.githubusercontent.com/8220722/84024022-b2aecc80-a9bb-11ea-8ef8-c61f7e0d5a0f.png)

**Comment by gavinman100** [comment]
谢谢楼主，果然可以了，是我"DOMAIN”变量设置有问题，再次非常感谢！
