### ISSUE TITLE
功能建议: 更新dns时有一个调起其他流程的方案

### ISSUE THREAD

**Issue by ZzMark** [sanjusss/aliyun-ddns#19]
目前我这里公网ip发生变更，在修改dns解析后，还有一些其他流程，比如要修改路由器的配置，做一下运维的信息推送

建议增加一个hook，更新dns时可以调用一个url触发其他流程，比如调用钉钉机器人、自有的ci系统等等

**Comment by sanjusss** [comment]
简单支持了一下钉钉的格式。
