### ISSUE TITLE
ARM64v8 0.2.2 无参数d

### ISSUE THREAD

**Issue by inphybj** [sanjusss/aliyun-ddns#26]
反馈：

ARM64v8 0.2.2-0.2.4 传不进去参数d，--help里面也没看到参数d。
0.2.1版目前正常使用中，没这个问题。

![搜狗截图20200624184242](https://user-images.githubusercontent.com/67384127/85594633-ae043c80-b67a-11ea-882f-c4c01abaca2e.png)

**Comment by sanjusss** [comment]
注释endpoint代码时搞错了

**Comment by inphybj** [comment]
刚刚更新了ARM64v8的0.2.5版，运行不了。
ARM Cortex-A57 
standard_init_linux.go:185: exec user process caused "exec format error"

**Comment by sanjusss** [comment]
> 刚刚更新了ARM64v8的0.2.5版，运行不了。
> ARM Cortex-A57
> standard_init_linux.go:185: exec user process caused "exec format error"

我现在没有arm的设备，是容器无法运行吗？我刚才换了个基础镜像，你拉取latest再试试。

**Comment by inphybj** [comment]
> > 刚刚更新了ARM64v8的0.2.5版，运行不了。
> > ARM Cortex-A57
> > standard_init_linux.go:185: exec user process caused "exec format error"
> 
> 我现在没有arm的设备，是容器无法运行吗？我刚才换了个基础镜像，你拉取latest版镜像再试试。

OK了, 感谢!
