### ISSUE TITLE
删除docker可以加入自动删除ddns记录吗？

### ISSUE THREAD

**Issue by cjiasu** [sanjusss/aliyun-ddns#4]
删除docker可以加入自动删除ddns记录吗？

**Comment by sanjusss** [comment]
容器中无法响应容器被删除的事件。停止的事件倒是可以响应

**Comment by cjiasu** [comment]
哦 哦 以前用CF的docker ddns可以删除docker那边记录也更着删了

C加速永久官网:https://cjswiki.github.io

司徒玟琅 <notifications@github.com> 于 2019年11月2日周六 下午4:58写道：
