### ISSUE TITLE
我服了 为什么网络占用这么高？

### ISSUE THREAD

**Issue by fistnine** [sanjusss/aliyun-ddns#56]
![image](https://user-images.githubusercontent.com/28135683/148345483-84e69e98-d84f-4299-9c3c-9b05ef6e2be8.png)

![image](https://user-images.githubusercontent.com/28135683/148345715-21e0523c-9650-408a-8907-98b68564b876.png)

**Comment by sanjusss** [comment]
有没有一段时间内消耗的总流量的统计呢？

**Comment by sanjusss** [comment]
每次更新时，是并发请求所有API网站获取公网IP，会造成那一小段时间流量突升。

**Comment by fistnine** [comment]
没有
我才发现一直是这样
![image](https://user-images.githubusercontent.com/28135683/148355808-e82fbc90-8e9c-4042-9b31-ffe2883f397f.png)

**Comment by sanjusss** [comment]
> 没有 我才发现一直是这样 ![image](https://user-images.githubusercontent.com/28135683/148355808-e82fbc90-8e9c-4042-9b31-ffe2883f397f.png)

![image](https://user-images.githubusercontent.com/8220722/148357613-db149b9e-ddd8-42c1-9804-b40ede3f4a9e.png)
我感觉像是群晖的统计问题，我这里用的是docker官方的统计，显示总流量，在每次请求之后就不增加了。

**Comment by fistnine** [comment]
好把 我有时间测试一下
