### ISSUE TITLE
更新ipv6地址的问题

### ISSUE THREAD

**Issue by zhanglinglingc** [sanjusss/aliyun-ddns#57]
请问现在可以成功更新ipv6地址了吗 是通过外部接口还是本地网卡 本地网卡的话docker需要做什么设置吗？

**Comment by sanjusss** [comment]
外部接口或本地网卡都可以。
docker获取本地网卡，需要指定容器参数`--net=host`，容器环境变量`CHECKLOCAL`为`true`。
https://github.com/sanjusss/aliyun-ddns#docker

**Comment by zhanglinglingc** [comment]
感谢解答 目前我是指定了使用host方式  然后默认采用了外部接口方式 对于变化的ipv6 理论上是可以正常更新解析的吧 因为网络上的教程说不能更新 但是我实际使用中 只指定了host模式 其他的没有更改（CHECKLOCALI PV6NETS均未开启） 也是可以正常更新解析

**Comment by zhanglinglingc** [comment]
谢谢解答
