### ISSUE TITLE
查看日志发现调用ipip接口会出现ip地址为127.0.0.1

### ISSUE THREAD

**Issue by jasonbohan** [sanjusss/aliyun-ddns#62]
以下为日志文件：
[04/22/2022 06:37:16]当前公网IPv4为 127.0.0.1（ipip.net接口）。

我在浏览器里 访问http://myip.ipip.net 时，在一分钟内刷新多次，也出现了本机IP地址为：127.0.0.1的情况

当前 IP：127.0.0.1  来自于：本机地址 本机地址   

是否是ipip.net插件问题。
不管是windows浏览器，还是linux的脚本，使用ipip.net 都出现了本机IP地址为127.0.0.1问题。

**Comment by sanjusss** [comment]
看来ipip.net开始限流了

**Comment by jasonbohan** [comment]
那是否可以不使用ipip.net了。从昨天开始就频繁出现127.0.0.1了。

司徒玟琅 ***@***.***>于2022年4月22日 周五08:35写道：

**Comment by sanjusss** [comment]
> 那是否可以不使用ipip.net了。从昨天开始就频繁出现127.0.0.1了。

我更新一下代码吧。

**Comment by jasonbohan** [comment]
请问docker 也会做相应的更新吗？因为我使用了的docker部署的

**Comment by sanjusss** [comment]
docker拉取0.2.7.1版本或latest。已经发布到docker hub上面了。

**Comment by jasonbohan** [comment]
感谢！已经用上了。
