### ISSUE TITLE
获取ip地址可以用淘宝的服务

### ISSUE THREAD

**Issue by lersh** [sanjusss/aliyun-ddns#8]
国内的话速度更快：http://ip.taobao.com/service/getIpInfo.php?ip=myip
目前代码里用的这个服务，在科学上网下会被自动转到梯子的线路上，我一开始发现我的地址和路由器里的不一致还一头雾水，后来才发现可能是梯子的问题

**Comment by sanjusss** [comment]
现在已经更新了镜像。
按如下顺序调用接口
- 淘宝
- IP-API
- ipv6-test
上一个接口失败才会调用下一个接口。淘宝的接口经常挂，很不稳定。
