### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 1196013153** [sanjusss/aliyun-ddns#9]
获取*******阿里云域名*****的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: SDK.WebException : HttpWebRequest WebException occured, the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.
--------------------------------------------------------------------------------------------
基本上没获取一次ip地址就会报一次错,虽然不影响使用,望解决,版本尝试多个版本都是一样的错误

**Comment by sanjusss** [comment]
你的运行参数是什么？可以把除密钥外的参数发一下看看吗（打码也行）？

**Comment by 1196013153** [comment]
运行环境群晖ds218,联通宽带
运行命令:  docker run -d --restart=always --net=host  --name="aliyun"   -e "AKID=*****"     -e "AKSCT=*****"     -e "DOMAIN=mydomain.com"     -e "ENDPOINT=cn-hangzhou"     -e "REDO=300"     -e "TTL=600"     -e "TIMEZONE=8.0"     -e "TYPE=A,AAAA"     sanjusss/aliyun-ddns:0.1.7
运行结果:
能正常获取到ip,并保存到阿里云dns解析,不影响使用,但同时也会报错如下:
![image](https://user-images.githubusercontent.com/43103611/74546172-1e8ca580-4f85-11ea-887c-e66ed43ef16c.png)

**Comment by sanjusss** [comment]
多半是宽带到阿里云之间的线路问题，明天我再详细看看

**Comment by sanjusss** [comment]
我看日志，有时可以获取现有的dns记录，有时不能。应该是联通的线路抽风，过几天应该就好了。
